### ISSUE TITLE
Require country_select_without_sort_alphabetical fails

### ISSUE THREAD

**Issue by koppen** [countries/country_select#210]
Following the instructions in the README, I added the following to my Gemfile:

    gem 'country_select', require: 'country_select_without_sort_alphabetical'

After bundling it seems to have been installed:

```
$ bundle list | grep country
  * country_select (8.0.0)
```

however, I get the following on launching the server:

```
$ rails server
~/.rvm/gems/ruby-3.0.1@bundler/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require': cannot load such file -- country_select_without_sort_alphabetical (LoadError)
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/bundler-2.3.6/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/bundler-2.3.6/lib/bundler/runtime.rb:55:in `each'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/bundler-2.3.6/lib/bundler/runtime.rb:55:in `block in require'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/bundler-2.3.6/lib/bundler/runtime.rb:44:in `each'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/bundler-2.3.6/lib/bundler/runtime.rb:44:in `require'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/bundler-2.3.6/lib/bundler.rb:176:in `require'
	from ~/Projects/app/config/application.rb:9:in `<main>'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332:in `block in require'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332:in `require'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/railties-6.1.4/lib/rails/commands/server/server_command.rb:138:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/railties-6.1.4/lib/rails/commands/server/server_command.rb:135:in `perform'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/railties-6.1.4/lib/rails/command/base.rb:69:in `perform'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/railties-6.1.4/lib/rails/command.rb:48:in `invoke'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/railties-6.1.4/lib/rails/commands.rb:18:in `<main>'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from ~/.rvm/gems/ruby-3.0.1@bundler/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by ron-shinall** [comment]
@koppen there was a breaking change in 8.0.0 that was mentioned in the [release notes](https://github.com/countries/country_select/releases/tag/v8.0.0). I also created https://github.com/countries/country_select/pull/211 to remove that reference from the readme.

**Comment by koppen** [comment]
The only breaking change I see in the release notes is related to `priority countries`, which we don't use, so I definitely missed that bit. 

The change in #211 would definitely have helped me - thanks! :)
